### ISSUE TITLE
Consider node publish status

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/indexnow#1]
Cool module!

I do have a question, though: is there a way to consider the node published status?

From what I see, that's currently not considered, so the bots get invited and stand before closed doors (403) when they arrive in case a new post isn't published yet. Is that correct? (I didn't try it out yet.)

**Comment by findlabnet** [comment]
Seems like my fault. Will be fixed ASAP.
Any more recommendations? Very appreciated for your feedback.

**Comment by findlabnet** [comment]
Fixed in new release. Thank you, @indigoxela !
